baseurl:     /
source:      ./src
destination: ./deploy
encoding:    utf-8
permalink:   /posts/:title
highlighter: pygments
markdown:    rdiscount
rdiscount:
  extensions:
    # - autolink
    - footnotes
    - smart

paginate: 10
paginate_path: '/posts/:num'

excerpt_separator: "\n\n\n"

ENV: develop
STATIC_HOST: 'http://static.hello13.net'
# STATIC_HOST: 'http://43.241.219.90:3030'

#Basic Configuration
title:       Hello13
subTitle:    While we could survive and hope will grow up.
description: Thanks for comming and Please star and fork in Github if u like here.

author:
  name: 有田十三
